name: neuro
channels:
  - defaults
dependencies:
  - pip=23.2.1
  - python=3.8
  - plotly=5.24.1
  - matplotlib=3.7.2
  - scipy=1.10.1
  - pandas=2.0.3
  - numpy=1.21.6
  - notebook=6.4.0
  - pip:
      - scikit-learn==1.3.2
      - jupyter-server==1.10.2
      - traitlets==5.9.0
      - h5py==2.10.0
      - mat73
      - kaleido
